# Generated by Django 4.2.13 on 2024-10-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='/media/images/luffy.png', upload_to='static/images/'),
        ),
    ]
