# Generated by Django 4.2.13 on 2024-06-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='idPost',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
