# Generated by Django 4.2.13 on 2024-06-08 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_idpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='descrip',
            new_name='descripcion',
        ),
    ]
