# Generated by Django 4.2.13 on 2024-06-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_descrip_post_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='banner',
            field=models.ImageField(blank=True, default='luffy.png', upload_to=''),
        ),
    ]
