# Generated by Django 4.2.13 on 2024-07-04 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_categoria_cliente_pedido_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categorias',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='posts.categoria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='posts.cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='productos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='posts.post'),
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
